### PR TITLE
Add encoder for NonEmptyString

### PR DESCRIPTION
**Pull request by d0liver**
Added an `EncodeJson` instance for `NonEmptyString`s and a test for the `EncodeJson` and `DecodeJson` instances for `NonEmptyString`s.

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a link to this PR and your username
- [x] Linked any existing issues or proposals that this pull request should close
- [x] Updated or added relevant documentation in the README and/or documentation directory
- [x] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Don't worry about the CI failures related to dependencies -- these are due to breaking changes being made in the PureScript 0.14 package set.

**Comment by garyb** [comment]
I'd suggest adding a `DecodeJson` instance for it at the same time, I think all the encode/decodes are paired just now 🙂

**Comment by garyb** [comment]
Oh, sorry, I just saw on Slack there already is one!

**Comment by thomashoneyman** [comment]
@garyb This fixes a slip where we'd only added a `DecodeJson` instance for `NonEmptyString` and not included an encoder as well. So no need in this case, though in general you're spot on!

**Comment by thomashoneyman** [comment]
Ah, you're too fast for me!

**Comment by garyb** [comment]
Funny that we both noticed within seconds of each other, 2 hours after I commented 🤣

**Review by thomashoneyman — APPROVED** [review]

**Pull request merged**
