### PR TITLE
Extract getField' from getField

### PR DESCRIPTION
**Pull request by techtangents**
We wanted to make a decoder for an object with fields, without having to create nested nominal types just to have DecodeJson instances.

### CODE REVIEW

**Comment by thomashoneyman** [comment]
Thanks for adding this, @techtangents! I'm sorry we've taken so long to get back to you but I agree this is a useful addition. I've joined the contrib organization to help us be more prompt (on the order of days) in the future.

I agree that it's useful to be able to decode and encode JSON without requiring instances. Ideally if this change goes through, there would be alternate versions of each of the encoding / decoding functions in the library, right? It seems like if there's a valid use case for this in `getField`, that same use case is reflected in `getFieldOptional`, etc.

Given that this is an entirely different way to use the library vs. the instance-based approach, perhaps it would be better to provide a separate module where all functions are named the same but the module itself is intended for a decoder function instead of a decode instance.

What do you think of providing explicit versions of each of these, rather than only the `getField` function?

**Comment by chexxor** [comment]
I like @thomashoneyman's idea. I like the idea of having a different module for a different way of accomplishing the same task.
The following example *may* be a little too different to be relevant here, but I'll reference it anyway.

I did similar to your proposal when adding a row type to describe the parameters of a mustache-template string in [my PR](https://github.com/svisser/purescript-mustache/pull/4) to the purescript-mustache library:

If someone wants `type Template = String`, they can `import Mustache (render)`, and if they want `type Template (i :: # Type) = String`, they can `import MustacheRecord (render)`

Source tree for that here: https://github.com/svisser/purescript-mustache/tree/abd63fe7ff1741c8a85c54d90be6a187527982f3/src

The only trouble with that is that a library *could* have many different solutions to the same problem, which makes it more difficult for new users of the library to choose a module. While this could be mitigated with package documentation and removing dangerously poor options, programmers could decide that having too many options is just not worth it. To resolve *that*, then, requires a policy of which types of alternate function designs are acceptable to include as part of the library, which can be tricky.

**Comment by thomashoneyman** [comment]
In this case the instances used for the type class module would literally be the functions defined in the non-type class module, and I think it's a pretty easy differentiation to pick up on as a user. I'd like to let this PR remain for another week or so @techtangents to give you a chance to weigh in; after that, I will most likely make it possible for all decode / encode combinators to be used with explicit functions or with instances.

**Comment by thomashoneyman** [comment]
Closing this for inactivity, but we can revisit the idea.

**Pull request closed without merging**
