### PR TITLE
Add support for decoding missing record fields to Nothing

### LINKED ISSUE #92: Support decoding of undefined record field to Nothing
**Is your change request related to a problem? Please describe.**

Can we support optional fields to Maybe? In particular, treat undefined values as Nothing.

Both should be decode to `{ a: Nothing }`
* `{}`
* `{"a": null}`

**Describe the solution you'd like**

I propose adding a new 

```
class DecodeJsonField a where 
  decodeJsonField :: Maybe Json -> Either JsonDecodeError a
```

and using it within the decoding.

I am also of the opinion of encoding `Nothing` should encode to an undefined field - but that can be a separate matter.

### PR DESCRIPTION
**Pull request by jvliwanag**
Decodes missing fields in a record as `Nothing`.

Adds a helper type class `DecodeJsonField`

Fixes #92

### CODE REVIEW

**Comment by thomashoneyman** [comment]
This is an interesting suggestion. From my reading, we're essentially moving from using `getField` for each field in a record:

https://github.com/purescript-contrib/purescript-argonaut-codecs/blob/9ce8e17dfa6ceb41dd867de3220a476c08d4d412/src/Data/Argonaut/Decode/Decoders.purs#L203-L213

to attempting to use `getFieldOptional` for each field, falling back to `getField`:

https://github.com/purescript-contrib/purescript-argonaut-codecs/blob/9ce8e17dfa6ceb41dd867de3220a476c08d4d412/src/Data/Argonaut/Decode/Decoders.purs#L215-L224

I'm intrigued, but this would be a significant change so I'd like to leave this open for a time to allow some discussion. Thank you for taking the time to write this up!

**Comment by jvliwanag** [comment]
Anything we can do to see this go through? Would love to use argonaut records directly for simple web api’s.

**Review by thomashoneyman — APPROVED** [review]

**Comment by thomashoneyman** [comment]
I'll leave this open for a little while to let other maintainers weigh in, but if I haven't merged it in a week please ping me and I will @jvliwanag -- thanks!

**Comment by garyb** [comment]
I'm fine with it - I probably wouldn't choose to have it work this way personally if I was designing a library from scratch, as I don't think you can distinguish between the field missing and having no value present now, right? But `Maybe` collapsing happens with the encoding used elsewhere already so it's already established that this library doesn't care about that kind of distinction.

**Comment by jvliwanag** [comment]
Are we good with this @thomashoneyman ? :)

On a side note, I do prefer `Nothing` be encoded as missing fields. I'll open a separate issue on that.

**Pull request merged**
