### PR TITLE
Add a combinator for decoding maybe fields

### PR DESCRIPTION
**Pull request by passy**
I'm not sure if this is something you want to include here, but I found it quite useful in my code.

This adds a (.??) combinator to decode optional fields, like (.:?) in Aeson. I'm not really sure how to add that to the existing test suite. Any help there would be much appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/purescript-contrib/purescript-argonaut-codecs/17)

### CODE REVIEW

**Comment by garyb** [comment]
Perhaps we could talk about it as an optional field rather than specifically a "maybe" field? As the intent is to handle fields that may not exist, not those that are maybe-typed, right?

**Comment by passy** [comment]
True. Do you think renaming the function from `getFieldMaybe` to `getFieldOptional` would address that?

**Comment by garyb** [comment]
That was exactly what I meant, sorry I wasn't clear :smile:

**Comment by passy** [comment]
@garyb No worries, just wanted to be sure. :) I've updated the name.

**Comment by garyb** [comment]
Thanks!

**Comment by passy** [comment]
Thanks for reviewing and merging! :)

**Pull request merged**
